name: Docs Tests

on:
  workflow_dispatch:

  push:
    branches: ['*']
    paths:
      - 'apps/docs/**/*.{ts,tsx}'
  pull_request:
    branches: ['*']
    paths:
      - 'apps/docs/**/*.{ts,tsx}'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm run test:docs
